# Generated by Django 5.2.4 on 2025-12-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Platform commission (10%)', max_digits=12),
        ),
    ]
